cropsmap = {
    'Alabama': 'poultry, cattle, eggs',
    'Alaska': 'greenhouse plants, hay, potatoes',
    'Arizona': 'dairy, cattle, greenhouse plants',
    'Arkansas': 'poultry, rice, soybeans',
    'California': 'dairy, greenhouse plants, grapes',
    'Colorado': 'cattle, dairy, corn',
    'Connecticut': 'greenhouse plants, dairy, eggs',
    'Delaware': 'poultry, corn, soybeans',
    'Florida': 'greenhouse plants, oranges, tomatoes',
    'Georgia': 'poultry, eggs, cotton',
    'Hawaii': 'greenhouse plants, sugarcane, macadamia nuts',
    'Idaho': 'dairy, cattle, potatoes',
    'Illinois': 'corn, soybeans, hogs',
    'Indiana': 'corn, soybeans, hogs',
    'Iowa': 'corn, soybeans, hogs',
    'Kansas': 'cattle, wheat, corn',
    'Kentucky': 'horses, poultry, corn',
    'Louisiana': 'rice, corn, sugarcane',
    'Maine': 'potatoes, dairy, eggs',
    'Maryland': 'poultry, greenhouse plants, corn',
    'Massachusetts': 'greenhouse plants, cranberries, diary',
    'Michigan': 'dairy, corn, soybeans',
    'Minnesota': 'corn, soybeans, hogs',
    'Mississippi': 'poultry, soybeans, corn',
    'Missouri': 'soybeans, corn, cattle',
    'Montana': 'wheat, cattle, barley',
    'Nebraska': 'cattle, corn, soybeans',
    'Nevada': 'cattle, hay, dairy',
    'New Hampshire': 'greenhouse plants, dairy, apples',
    'New Jersey': 'greenhouse plants, horses/mules, blueberries',
    'New Mexico': 'dairy, cattle, hay',
    'New York': 'dairy, greenhouse plants, corn',
    'North Carolina': 'poultry, hogs, greenhouse plants',
    'North Dakota': 'wheat, soybeans, corn',
    'Ohio': 'corn, soybeans, dairy',
    'Oklahoma': 'cattle, wheat, hogs',
    'Oregon': 'greenhouse plants, cattle, dairy',
    'Pennsylvania': 'dairy, cattle, eggs',
    'Rhode Island': 'greenhouse plants, dairy, corn',
    'South Carolina': 'poultry, greenhouse plants, turkeys',
    'South Dakota': 'corn, cattle, soybeans',
    'Tennessee': 'cattle, poultry, soybeans',
    'Texas': 'cattle, cotton, dairy',
    'Utah': 'dairy, cattle, hay',
    'Vermont': 'dairy, cattle, greenhouse plants',
    'Virginia': 'poultry, cattle, dairy',
    'Washington': 'apples, dairy, wheat',
    'West Virginia': 'poultry, cattle, turkeys',
    'Wisconsin': 'dairy, corn, cattle',
    'Wyoming': 'cattle, hay, hogs'
    }
